name: django CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - run: cp ~/.env ./etradingview/
      - run: sudo docker build --tag isalgo .
      - run: sudo docker -d run --publish 80:8000 isalgo