name: django CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - run: cp ~/.env ./etradingiew
      - run: docker build --tag isalgo .
      - run: docker run --publish 80:8000 isalgo